article/urls.py
from django.urls import path
from .views import ArticleDetail, Home, About, CategoryArticleList, TagArticleList, SearchArticleList

app_name = 'article'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('searcharticlelist/', SearchArticleList.as_view(), name='searchArticleList'),
    path('categoryarticlelist/<int:pk>', CategoryArticleList.as_view(), name='categoryArticleList'),
    path('tagarticlelist/<int:pk>', TagArticleList.as_view(), name='tagArticleList'),
    path('articledetail/<int:pk>/', ArticleDetail.as_view(), name='articleDetail'),     # pk主键用在django类视图
    path('about/', About.as_view(), name='about'),
]

userprofile/urls.py
from django.urls import path
from .views import Login, Logout, Register

app_name = 'userprofile'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
]

userprofile/models.py
from django.db import models

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()

class UserRegisterForm(forms.ModelForm):
    password1 = forms.CharField()
    password2 = forms.CharField()
    class Meta:
        model = User
        fields = ('username', 'email',)
    # 对两次输入的密码进行校验
    def clean_password2(self):
        data = self.cleaned_data    # cleaned_data函数根据表单字段清洗出合法数据(字典类型数据)
        pwd1 = data.get('password1')
        pwd2 = data.get('password2')
        if pwd1 == pwd2:
            return pwd1
        else:
            raise forms.ValidationError('密码一和密码二不一致，请检查。')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from .forms import UserLoginForm, UserRegisterForm
from django.views.generic import RedirectView

class Login(RedirectView):
    def get(self, request, *args, **kwargs):
        if self.request.method == 'POST':
            userLoginForm = UserLoginForm(data=self.request.POST)
            if userLoginForm.is_valid():
                # cleaned_data函数根据表单字段清洗出合法数据(字典类型数据)
                data = userLoginForm.cleaned_data
                # 验证账户和密码能否匹配数据库中的某一个用户
                userr = authenticate(username=data.get('username'), password=data['password'])  # data['name'] 取值如果没有name属性将报错, data.get()就不会报错
                if userr:
                    # 保存到seesion
                    login(self.request, userr)
                    # return HttpResponseRedirect(reverse('article:home'))
                    return redirect('article:home')
                else:
                    return HttpResponse('账户或密码不正确，请修改。')
            else:
                return HttpResponse('账号或密码输入不合法')
        elif self.request.method == 'GET':
            userLoginForm = UserLoginForm()
            context = {'form': userLoginForm}
            return render(self.request, 'userprofile/login.html', context)
        else:
            return HttpResponse('只能使用POST或GET请求数据。')

class Logout(RedirectView):
    def get(self, request, *args, **kwargs):
        # 清除seesion
        logout(request)
        return redirect('article:home')

class Register(RedirectView):
    def get(self, request, *args, **kwargs):
        if request.method == 'POST':
            userRegisterForm = UserRegisterForm(data=request.POST)
            if userRegisterForm.is_valid():
                newUser = userRegisterForm.save(commit=False)
                data = userRegisterForm.cleaned_data
                pwd = data.get('password1')
                newUser.set_password(pwd)
                newUser.save()
                if request.user.is_authenticated:
                    logout(request)
                login(request, newUser)
                return redirect('article:home')
            else:
                return HttpResponse('注册表单有错误。')
        elif request.method == 'GET':
            userRegisterForm = UserRegisterForm()
            context = {'userRegisterForm': userRegisterForm}
            return render(request, 'userprofile/register.html', context)
        else:
            return HttpResponse('请使用GET或POST请求。')

templates/userprofile/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}登陆{% endblock title %}
{% block content %}
<div class="container">
    <div class="modal-dialog" style="margin-top: 13%;">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title text-center" id="loginModalLabel">登陆</h2>
            </div>
            <form class="modal-body" id="model-body" method="POST" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="username" name="username" placeholder="用户名" autofocus="autofocus" autocomplete="off" maxlength="20" required="">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" id="password" name="password" placeholder="密码" autocomplete="off" maxlength="15" required="">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control" id="submit" name="submit">登陆</button>
                </div>
            </form>
            <div class="modal-footer">
                <a style="display:block;text-align:center;" data-target="{% url 'userprofile:register' %}"; href="{% url 'userprofile:register' %}">还没有账号？点我注册</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}注册{% endblock title %}
{% block content %}
<div class="container">
    <div class="modal-dialog" style="margin-top: 13%;">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title text-center" id="loginModalLabel">注册</h2>
            </div>
            <form class="modal-body" id="model-body" method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="username" name="username" placeholder="用户名" autofocus="autofocus" autocomplete="off" maxlength="20" required="">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" id="email" name="email" placeholder="邮箱" autocomplete="off" required="">
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" id="password1" name="password1" placeholder="密码" autocomplete="off" maxlength="15" required="">
                </div>

                <div class="form-group">
                    <input type="password" class="form-control" id="password2" name="password2" placeholder="确认密码" autocomplete="off" maxlength="15" required="">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary form-control" id="submit" name="submit">注册</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}