article/urls.py
from django.urls import path
from .views import ArticleDetail, Home, About, CategoryArticleList, TagArticleList, SearchArticleList

app_name = 'article'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('searcharticlelist/', SearchArticleList.as_view(), name='searchArticleList'),
    path('categoryarticlelist/<int:pk>', CategoryArticleList.as_view(), name='categoryArticleList'),
    path('tagarticlelist/<int:pk>', TagArticleList.as_view(), name='tagArticleList'),
    path('articledetail/<int:pk>/', ArticleDetail.as_view(), name='articleDetail'),     # pk主键用在django类视图
    path('about/', About.as_view(), name='about'),
]

userprofile/urls.py
from django.urls import path
from .views import Login, Logout, Register

app_name = 'userprofile'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
]

templates/base.html
<!doctype html>
<html lang="zh-cn">
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %}</title>
	<meta name="keywords" content="">
	<meta name="description" content="">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/nprogress.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="apple-touch-icon-precomposed" href="{% static 'images/icon.png' %}">
	<link rel="shortcut icon" href="{% static 'images/News.ico' %}">
	<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/nprogress.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.lazyload.min.js' %}"></script>
	<!--[if gte IE 9]>
	<script src="{% static 'js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/html5shiv.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/respond.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'js/selectivizr-min.js' %}" type="text/javascript"></script>
	<![endif]-->
	<!--[if lt IE 9]>
	<script>window.location.href='upgrade-browser.html';</script>
	<![endif]-->
	<style type="text/css">
		html, body {
            height: 100%;
            margin: 0;
        }

        #wrapper {
            min-height: 100%;
        }

		img.topRecommend:hover {
			border: 1px solid #42B5EF;
		}

		p {
			-webkit-user-select:text;
			-moz-user-select:text;
			-ms-user-select:text;
			user-select:text;
		}
	</style>
</head>
<body class="user-select">
	{% include 'header.html' %}
	<div id="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
	{% include 'footer.html' %}
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery.ias.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
	<!--
	<script src="{% static 'jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'popper/popper.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    -->
</body>
</html>

templates/footer.html
{% load static %}
<footer class="footer">
    <div class="container">
        <p>Copyright &copy; 2020.www.quantity123.com All rights reserved</p>
    </div>
</footer>

templates/header.html
{% load static %}
<header class="header">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container">
            <div class="header-topbar hidden-xs link-border">
                看新闻 长知识
            </div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1 class="logo hvr-bounce-in" align-title="center">
                    <a href="{% url 'article:home' %}" title="新闻速览">新闻速览</a>
                </h1>
            </div>
            <div class="collapse navbar-collapse" id="header-navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item">
                        <a class="nav-link" data-cont="首页" title="首页" href="{% url 'article:home' %}">首页</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
                        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" data-cont="退出登陆" href="{% url 'userprofile:logout' %}">退出登陆</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" data-cont="登陆" title="登陆" href="{% url 'userprofile:login' %}">登陆</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" data-cont="关于" title="关于" href="{% url 'article:about' %}">关于</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>