article/urls.py
from django.urls import path
from .views import ArticleDetail, Home, About, CategoryArticleList, TagArticleList, SearchArticleList

app_name = 'article'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('searcharticlelist/', SearchArticleList.as_view(), name='searchArticleList'),
    path('categoryarticlelist/<int:pk>', CategoryArticleList.as_view(), name='categoryArticleList'),
    path('tagarticlelist/<int:pk>', TagArticleList.as_view(), name='tagArticleList'),
    path('articledetail/<int:pk>/', ArticleDetail.as_view(), name='articleDetail'),     # pk主键用在django类视图
    path('about/', About.as_view(), name='about'),
]

comment/urls.py
from django.urls import path
from .views import ArticleComment

app_name = 'comment'

urlpatterns = [
    path('articlecomment/<int:pk>', ArticleComment.as_view(), name='articleComment'),
]

userprofile/urls.py
from django.urls import path
from .views import Login, Logout, Register

app_name = 'userprofile'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('register/', Register.as_view(), name='register'),
]

article/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

class Category(models.Model):
    name = models.CharField('分类名称', max_length=100)
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['pk']
    def __str__(self):      # 当html模板用{{ 分类实例对象 }}取值时候调用__str__函数返回值
        return self.name

class Tag(models.Model):
    name = models.CharField('标签名称', max_length=100)
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['pk']
    def __str__(self):
        return self.name

class Article(models.Model):
    title = models.CharField('标题', max_length=100)
    body = models.TextField('正文')
    category = models.ForeignKey(Category, verbose_name='分类', related_name='article', on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    viewCount = models.PositiveIntegerField(default=0, editable=False)
    commentCount = models.PositiveIntegerField(default=0, editable=False)
    iconograph = models.ImageField(upload_to='articleIconograph/', blank=True)
    topRecommend = models.BooleanField(verbose_name='推荐', default=False)
    createdTime = models.DateTimeField('创建时间', default=timezone.now)
    modifiedTime = models.DateTimeField('修改时间', auto_now=True)  # auto_now 每次数据更新时自动写入当前时间
    author = models.ForeignKey(User, verbose_name='作者', related_name='article', on_delete=models.CASCADE)
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-createdTime']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('article:articleDetail', args=(self.id,))
    def increase_viewCount(self):
        self.viewCount += 1
        self.save(update_fields=['viewCount'])
    def save(self, *args, **kwargs):
        article = super(Article, self).save(*args, **kwargs)
        if self.iconograph and not kwargs.get('update_fields'):
            image = Image.open(self.iconograph)
            x, y = image.size
            newX = 820
            newY = 400
            resizedImage = image.resize((newX, newY), Image.ANTIALIAS)
            resizedImage.save(self.iconograph.path)
        return article
    def was_createdTime_recently(self):
        diff = timezone.now() - self.createdTime
        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            return True
        else:
            return False

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'body', 'iconograph',)

article/views.py
from .models import Article, Category, Tag
from django.views.generic import ListView, DetailView, TemplateView
from django.db.models import Q
from comment.models import Comment
from django.shortcuts import render, get_object_or_404

class CommonList(ListView):
    model = Article
    context_object_name = 'articleList'
    template_name = 'article/articleList.html'
    paginate_by = 10  # 一页显示10个记录
    def get_queryset(self):
        self.order = self.request.GET.get('order')   # ?后面根据键获取值
        if self.order == 'hot_order':
            return super(CommonList, self).get_queryset().order_by('-viewCount')
        else:
            return super(CommonList, self).get_queryset()
    def get_context_data(self, **kwargs):
        context = super(CommonList, self).get_context_data(**kwargs)
        context['categoryList'] = Category.objects.all()
        context['tagList'] = Tag.objects.all()
        context['order'] = self.order
        return context

class Home(CommonList):
    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        context['topRecommendArticleList'] = super(Home, self).get_queryset().filter(topRecommend=True)
        context['filterType'] = 0
        return context

class SearchArticleList(CommonList):
    def get_queryset(self):
        self.searchText = self.request.GET.get('searchText')
        return super(SearchArticleList, self).get_queryset().filter(Q(title__icontains=self.searchText)|Q(body__icontains=self.searchText))
    def get_context_data(self, **kwargs):
        context = super(SearchArticleList, self).get_context_data(**kwargs)
        context['filterType'] = 1
        context['searchText'] = self.searchText
        return context

class CategoryArticleList(CommonList):
    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs.get('pk'))   # url 内部获取参数值
        return super(CategoryArticleList, self).get_queryset().filter(category=self.category)
    def get_context_data(self, **kwargs):
        context = super(CategoryArticleList, self).get_context_data(**kwargs)
        context['filterType'] = 2
        context['category'] = self.category
        return context

class TagArticleList(CommonList):
    def get_queryset(self):
        self.tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagArticleList, self).get_queryset().filter(tag=self.tag)
    def get_context_data(self, **kwargs):
        context = super(TagArticleList, self).get_context_data(**kwargs)
        context['filterType'] = 3
        context['tag'] = self.tag
        return context

class ArticleDetail(DetailView):
    model = Article
    context_object_name = 'articleDetail'
    template_name = 'article/articleDetail.html'
    def get_object(self, queryset=None):
        articleDetail = super(ArticleDetail, self).get_object(queryset=None)
        articleDetail.increase_viewCount()
        return articleDetail
    def get_context_data(self, **kwargs):
        context = super(ArticleDetail, self).get_context_data(**kwargs)
        context['categoryList'] = Category.objects.all()
        context['tagList'] = Tag.objects.all()
        context['commentList'] = Comment.objects.filter(article=self.object.id)
        return context

class About(TemplateView):
    template_name = 'article/about.html'

templates/article/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}关于{% endblock title %}
{% block content %}
<section class="container">
	<article class="col-md-13">
		<div class="entry-content clearfix panel panel-default" style="height:800px">
			<article class="article-content">
				<div class="page-header">
					<img src="{% static 'images/about.jpg' %}" style="width:450px; height:450px">
				</div>
				<div class="media-body">
					<p class="lead" style="">
						介绍下,本人学习Python和Web服务端开发并且每天喜欢看新闻长长知识所以就用django框架制作了这个小新闻博客,并把看过的感兴趣的新闻
						转发(能合法转发的)到此处与互联网有缘人一起观赏讨论,如果想与本人联系可以发电子邮箱283186660@qq.com,此网站源码也是开源在了本人github上面,
						网址https://github.com/quantity123/QttNewsWebsite,有问题多多指教,谢谢!
					</p>
				</div>
			</article>
			<!--
			<h2 class="title text-center">社交媒体</h2>
			<ul class="social">
				<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
				<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
				<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
				<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
			</ul>
			-->
		</div>
	</article>
</section>
{% endblock content %}

templates/article/articleDetail.html
{% extends "base.html" %}
{% load static %}
{% block title %}新闻详情{% endblock title %}
{% block content %}
<section class="container">
    <div class="content-wrap">
        <div class="content">
            <header class="article-header">
                <h1 class="article-title">
                    <a href="#" title="{{ articleDetail.title }}">{{ articleDetail.title }}</a>
                </h1>
                <div class="article-meta">
                    <span class="item article-meta-views" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="浏览数">
                        <i class="glyphicon glyphicon-eye-open"></i> {{ articleDetail.viewCount }}
                    </span>
                    <span class="item article-meta-comment" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="评论数">
                        <i class="glyphicon glyphicon-comment"></i> {{ articleDetail.commentCount }}
                    </span>
                    <span class="item article-meta-time">
                        <time class="time" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="首次发表时间">
                            <i class="glyphicon glyphicon-time"></i> {{ articleDetail.createdTime }}
                        </time>
                    </span>
                    <span class="item article-meta-time">
                        <time class="time" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="最后修改时间">
                            <i class="glyphicon glyphicon-time"></i> {{ articleDetail.modifiedTime }}
                        </time>
                    </span>
                </div>
            </header>
            <article class="article-content">
                {% if articleDetail.iconograph %}
                <p><img data-original="{{ articleDetail.iconograph.url }}" src="{{ articleDetail.iconograph.url }}" alt="新闻插图"></p>
                {% endif %}
                <p>{{ articleDetail.body }}</p>
            </article>
            <hr>
            {% if user.is_authenticated %}
            <div class="title" id="comment">
                <h3>评论</h3>
            </div>
            <div id="respond">
                <form id="comment-form" name="comment-form" action="{% url 'comment:articleComment' articleDetail.id %}" method="POST">
                    {% csrf_token %}
                    <div class="comment">
                        <div class="comment-box">
                            <textarea type="text" class="form-control" style="max-width:808px;min-width:808px;" id="text" name="text" rows="3" placeholder="您的评论或留言(必填)"></textarea>
                            <div class="comment-ctrl">
                                <div class="comment-prompt" style="display:none;">
                                    <i class="fa fa-spin fa-circle-o-notch"></i>
                                    <span class="comment-prompt-text">评论正在提交中...请稍后</span>
                                </div>
                                <div class="comment-success" style="display:none;">
                                    <i class="fa fa-check"></i>
                                    <span class="comment-prompt-text">评论提交成功...</span>
                                </div>
                                <button type="submit" name="comment-submit" id="comment-submit" tabindex="4">发表</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            {% else %}
            <h4 class="row text-center">需<a href="{% url 'userprofile:login' %}">登陆</a>后回复</h4>
            <br>
            {% endif %}
            <h4>共有{{ commentList.count }}条评论</h4>
            <div id="postcomments">
                <ol id="comment_list" class="commentlist">
                    {% for comment in commentList %}
                    <li class="comment-content">
                        <span class="comment-f">{{ forloop.counter }}</span>
                        <div class="comment-main">
                            <p>
                                <a class="address" href="#" rel="nofollow">{{ comment.user.username }}</a>
                                <span class="time">({{ comment.createdTime }})</span>
                                <br>
                                {{ comment.text }}
                            </p>
                        </div>
                    </li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
    {% include 'article/aside.html' %}
</section>
{% endblock content %}

templates/article/articleList.html
{% extends "base.html" %}
{% load static %}
{% block title %}新闻速览{% endblock title %}
{% block content %}
<section class="container">
    <!--
    <div id="focusslide" class="carousel slide" data-ride="carousel">
        {% for topRecommendArticle in topRecommendArticleList %}
        <ol class="carousel-indicators">
            {% if forloop.first %}
            <li data-target="#focusslide" data-slide-to="forloop.counter0" class="active"></li>
            {% else %}
            <li data-target="#focusslide" data-slide-to="forloop.counter0"></li>
            {% endif %}
        </ol>
        <div class="carousel-inner" role="listbox">
            {% if forloop.first %}
            <div class="item active">
            {% else %}
            <div class="item">
            {% endif %}
                <a href="{{ topRecommendArticle.get_absolute_url }}" title="{{ topRecommendArticle.title }}">
                    <img src="{{ topRecommendArticle.iconograph.url }}" alt="{{ topRecommendArticle.title }}" class="img-responsive">
                </a>
            </div>
        </div>
        {% empty %}
        <ol class="carousel-indicators">
            <li data-target="#focusslide" data-slide-to="0" class="active"></li>
            <li data-target="#focusslide" data-slide-to="1" class=""></li>
            <li data-target="#focusslide" data-slide-to="2" class=""></li>
            <li data-target="#focusslide" data-slide-to="3" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <a href="#" title="无置顶推荐新闻">
                    <img src="{% static 'images/20200107073358489.jpg' %}" alt="无置顶推荐新闻" class="img-responsive">
                </a>
            </div>
            <div class="item">
                <a href="#" title="无置顶推荐新闻">
                    <img src="{% static 'images/20200107073358489.jpg' %}" alt="无置顶推荐新闻" class="img-responsive">
                </a>
            </div>
            <div class="item">
                <a href="#" title="无置顶推荐新闻">
                    <img src="{% static 'images/20200107073358489.jpg' %}" alt="无置顶推荐新闻" class="img-responsive">
                </a>
            </div>
            <div class="item">
                <a href="#" title="无置顶推荐新闻">
                    <img src="{% static 'images/20200107073358489.jpg' %}" alt="无置顶推荐新闻" class="img-responsive">
                </a>
            </div>
        </div>
        {% endfor %}
        <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">上一个</span>
        </a>
        <a class="right carousel-control" href="#focusslide" role="button" data-slide="next" rel="nofollow">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">下一个</span>
        </a>
    </div>
    -->
    {% if filterType == 0 %}
    <article>
        {% for topRecommendArticle in topRecommendArticleList %}
        <a href="{{ topRecommendArticle.get_absolute_url }}" title="{{ topRecommendArticle.title }}">
            <img class="topRecommend" data-original="{{ topRecommendArticle.iconograph.url }}" src="{{ topRecommendArticle.iconograph.url }}" alt="{{ topRecommendArticle.title }}" width="395", height="295"/>
        </a>
        {% empty %}
        {% endfor %}
    </article>
    <br>
    {% endif %}
    <div class="content-wrap">
        <div class="content">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    {% if filterType == 0 %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:home' %}">时间排序</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:home' %}?order=hot_order">热门排序</a>
                    </li>
                    {% elif filterType == 1 %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:searchArticleList' %}?searchText={{ searchText }}">时间排序</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:searchArticleList' %}?searchText={{ searchText }}&order=hot_order">热门排序</a>
                    </li>
                    {% elif filterType == 2 %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:categoryArticleList' category.pk %}">时间排序</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:categoryArticleList' category.pk %}?order=hot_order">热门排序</a>
                    </li>
                    {% elif filterType == 3 %}
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:tagArticleList' tag.pk %}">时间排序</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{% url 'article:tagArticleList' tag.pk %}?order=hot_order">热门排序</a>
                    </li>
                    {% endif %}
                </ol>
            </nav>
            {% for article in articleList %}
            <article class="excerpt excerpt-1">
                {% if article.iconograph %}
                <a class="focus" href="{{ article.get_absolute_url }}" title="{{ article.title }}">
                    <img class="thumb" data-original="{{ article.iconograph.url }}" src="{{ article.iconograph.url }}" alt="新闻插图" style="display: inline;">
                </a>
                {% endif %}
                <header>
                    <h2>
                        <a href="{{ article.get_absolute_url }}" title="{{ article.title }}"> {{ article.title }}</a>
                    </h2>
                </header>
                <p class="meta">
                    <span class="views" title="浏览数">
                        <i class="glyphicon glyphicon-eye-open"></i> {{ article.viewCount }}
                    </span>
                    <a class="comment" href="##comment" title="评论数">
                        <i class="glyphicon glyphicon-comment"></i> 4
                    </a>
                    <time class="time" title="首次发表时间">
                        <i class="glyphicon glyphicon-time"></i> {{ article.createdTime }}
                    </time>
                    <time class="time" title="最后修改时间">
                        <i class="glyphicon glyphicon-time"></i> {{ article.modifiedTime }}
                    </time>
                </p>
                <p class="note">
                    {{ article.body|slice:'100' }}...
                </p>
            </article>
            {% empty %}
                无新闻
            {% endfor %}
        </div>
    </div>
    {% include 'article/aside.html' %}
</section>
{% include 'article/pagination.html' %}
{% endblock content %}

templates/article/aside.html
{% load static %}
<aside class="sidebar">
    {% if articleDetail %}
    <div class="fixed" style="margin-top:110px">
    {% else %}
    <div class="fixed" style="margin-top:56px">
    {% endif %}
        <div class="widget widget-search">
            <form class="navbar-form" action="{% url 'article:searchArticleList' %}" method="GET">
                <div class="input-group">
                    <input type="search" name="searchText" class="form-control" size="35" placeholder="搜索新闻标题与内容关键字" maxlength="15" autocomplete="off" required>
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-search" type="submit">搜索</button>
                    </span>
                </div>
            </form>
        </div>

        <div class="widget widget-category">
            <h3 class="widget-title">分类</h3>
            <ul>
                {% for category in categoryList %}
                <li class="list-group-item">
                    <a href="{% url 'article:categoryArticleList' category.pk %}">{{ category }}</a>
                </li>
                {% empty %}
                    无分类
                {% endfor %}
            </ul>
        </div>

        <div class="widget widget-tag-cloud">
            <h3 class="widget-title">标签云</h3>
            <div class="article-tags">
                {% for tag in tagList %}
                <a href="{% url 'article:tagArticleList' tag.pk %}">{{ tag }}</a>
                {% empty %}
                    无标签
                {% endfor %}
            </div>
        </div>

        <div class="widget widget_sentence">
            <h3 class="widget-title">友情链接</h3>
            <p class="widget-sentence-link">
                <a href="https://github.com/quantity123" title="我的Github" target="_blank">我的Github</a>
            </p>
        </div>
    </div>

    <!--
    广告图片
    <div class="widget widget_sentence">
        <a href="#" target="_blank" rel="nofollow" title="图片广告" ><img style="width: 100%" src="images/201610241224221511.jpg" alt="图片广告"></a>
    </div>
    -->

    <!--
    随机推荐
    <div class="relates">
        <div class="title">
            <h3>随机推荐</h3>
        </div>
        <ul>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
            <li><a href="#" title="" >用DTcms做一个独立博客网站（响应式模板）-MZ-NetBlog主题</a></li>
        </ul>
    </div>
    -->
</aside>

templates/article/pagination.html
{% load static %}
{% if is_paginated %}
<div class="pagination-simple" align="center" style="margin-left:-290px">
    {% if page_obj.has_previous %}
        {% if order == 'hot_order' %}
            {% if filterType == 1 %}
                <a href="?page={{ page_obj.previous_page_number }}&searchText={{ searchText }}&order=hot_order">上一页</a>
            {% else %}
                <a href="?page={{ page_obj.previous_page_number }}&order=hot_order">上一页</a>
            {% endif %}
        {% else %}
            {% if filterType == 1 %}
                <a href="?page={{ page_obj.previous_page_number }}&searchText={{ searchText }}">上一页</a>
            {% else %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}
        {% endif %}
    {% endif %}
    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
    {% if page_obj.has_next %}
        {% if order == 'hot_order' %}
            {% if filterType == 1 %}
                <a href="?page={{ page_obj.next_page_number }}&searchText={{ searchText }}&order=hot_order">下一页</a>
            {% else %}
                <a href="?page={{ page_obj.next_page_number }}&order=hot_order">下一页</a>
            {% endif %}
        {% else %}
            {% if filterType == 1 %}
                <a href="?page={{ page_obj.next_page_number }}&searchText={{ searchText }}">下一页</a>
            {% else %}
                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}
        {% endif %}
    {% endif %}
    <!--跳至<input type="text" style="width:5em;">页<a href="#">GO</a>-->
</div>
<br>
{% endif %}